# Generated by Django 4.1.4 on 2022-12-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='tasks.user', verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='tasks.user', verbose_name='executor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='is_visible'),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_executer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is_executer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
