# Generated by Django 4.1.4 on 2022-12-27 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('bd336897-fb7d-44dd-b06a-6bd37d7d10d7'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('bd336897-fb7d-44dd-b06a-6bd37d7d10d7'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.TextField(choices=[('creator', 'creator'), ('executor', 'executor')], verbose_name='Role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_3744fd_idx'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='tasks.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='executor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='tasks.user'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_completed', 'creator_id', 'executor_id'], name='task_is_comp_3cfb65_idx'),
        ),
    ]
