# Generated by Django 4.1.4 on 2022-12-27 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_task_is_comp_3cfb65_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegramm_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dae806a6-39e9-4f3e-af35-8a3534e9281f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dae806a6-39e9-4f3e-af35-8a3534e9281f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
