# Generated by Django 4.1.4 on 2022-12-28 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_user_telegramm_id_alter_task_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('3afe4f81-7f2f-4595-8bd8-accf74fdadef'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'db_table': 'status',
            },
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='task_status__907d71_idx',
            old_name='task_status_678c32_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3afe4f81-7f2f-4595-8bd8-accf74fdadef'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3afe4f81-7f2f-4595-8bd8-accf74fdadef'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['title'], name='status_title_8da31b_idx'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='tasks.status'),
        ),
    ]
