# Generated by Django 4.1.4 on 2022-12-28 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_task_status__907d71_idx_task_status_678c32_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6904a9bb-3e5c-465e-98b7-17b2c201e09a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('created', 'created'), ('executed', 'executed'), ('deprecated', 'deprecated'), ("<class 'tasks.models.Status.Meta'>", 'Meta')], default='created', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6904a9bb-3e5c-465e-98b7-17b2c201e09a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
