# Generated by Django 4.1.4 on 2022-12-28 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_id_alter_task_status_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c8203db-d062-4e97-824e-8be485e5c374'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c8203db-d062-4e97-824e-8be485e5c374'), editable=False, primary_key=True, serialize=False),
        ),
    ]
