# Generated by Django 4.1.4 on 2022-12-28 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='note_chanal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegramm_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('436e4c4f-a850-495d-9ba1-7e4d93dbbdfb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('436e4c4f-a850-495d-9ba1-7e4d93dbbdfb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
