# Generated by Django 4.1.4 on 2022-12-28 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_user_note_chanal_remove_user_telegramm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('edfa4265-e7a1-491d-8d9e-4360a4bb8ddb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42d1b567-ea59-4811-a89d-36efe9ae278d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
