# Generated by Django 4.1.4 on 2022-12-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_id_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='note',
        ),
    ]
