# Generated by Django 4.1.4 on 2022-12-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_rename_content_task_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='executor_id',
            new_name='executor',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='task_status_f53a49_idx',
            old_name='task_status_678c32_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('creator', 'creator'), ('executor', 'executor')], db_index=True, verbose_name='Role'),
        ),
    ]
