# Generated by Django 4.1.4 on 2022-12-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_creator_id_task_creator_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_3744fd_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_executer',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
