# Generated by Django 4.1.4 on 2022-12-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_user_user_role_3744fd_idx_remove_user_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time_create',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_update',
            new_name='time_updated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='time_create',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='time_update',
            new_name='time_updated',
        ),
    ]
